### PR TITLE
Michael

### PR DESCRIPTION
**Pull request by devllapi**
Maze level added and art pass started, more to come soon

### CODE REVIEW

**Comment by RahulJoshi1997** [comment]
I'm good with this.

**Comment by bradengammon** [comment]
Looks good.

**Comment by RahulJoshi1997** [comment]
The Floor Control in your version is probably conflicting with my updated one. It should be fine to discard the floor control in your branch in favor of the floor control in master.

**Comment by bradengammon** [comment]
I seemed to have missed on my phone that there's a merge conflict. Probably close this, fix the conflict, the commit and make a new pull request?

**Comment by devllapi** [comment]
Ok im gonna look at the merge conflict later on tonight, sorry about that

**Comment by RahulJoshi1997** [comment]
Just copy and paste the master's floor control and have that be your floor control. It should be fine.

**Comment by bradengammon** [comment]
Actually @devllapi , I think that you will be able to reopen this pull request because it will use the most recent commit on the branch you want to merge. So:
* make the merge conflict fix (follow Rahul's suggestion)
* commit the fix
* push the commit to GitHub
* reopen this pull request. It should say there are no conflicts now
* we will see the slackbot post that the request has been reopened, and we can re-approve it.

**Pull request closed without merging**
